[profile.default]
solc = "0.8.17"
bytecode_hash = "none"
optimizer_runs = 1000000
via_ir = true

remappings = [
  "@solbase=lib/solbase/src/"
]

gas_reports = ["Helios", "HeliosReference"]

[profile.intense.fuzz]
runs = 10000
